services:
  server:
    container_name: iron-journal-server
    image: iron-journal-server:1.0
    build:
      context: ./Backend
      dockerfile: /app/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      translation-worker:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/iron-journal
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://root:password@redis:6379
      - SERVER_AUTH_TOKEN=iron-journal-server-auth-token
      - DISCORD_WEBHOOK_URL_REPORTER=https://discordapp.com/api/webhooks/1358479392401264732/7JluM_XEcx_wzXQraN4WiEOC6pnl6hnkaM0TmecNQOTD01Wwi_fX0TXW309ZUS3tPtGf
      - DISCORD_WEBHOOK_URL_FEEDBACK=https://discordapp.com/api/webhooks/1358479227720044576/ETC_EVjsi4u1GRzwA7e2j7nQShrVUTfpCWPP-PsMjms_zP9TaYKntT3mKxzOXCIiB6Hl
      - DISCORD_WEBHOOK_URL_ERROR=https://discordapp.com/api/webhooks/1358499230129455288/H2om3B9pT1CNNAY1I4WsGBgvNOJ5V-s9sgWEzF-VZ7gvqJDtAVonkllj2PxP0TdMBAFh
    networks:
      - app-network

  discord-bot:
    build: ./Discord-Bot
    container_name: discord-bot
    env_file: ./Discord-Bot/.env
    restart: unless-stopped
    depends_on:
      server:
        condition: service_started
    networks:
      - app-network

  translation-worker:
    container_name: iron-journal-translation-worker
    image: iron-journal-translation-worker:1.0
    build: ./translation-worker/
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/iron-journal
      - LIBRETRANSLATE_URL=http://libretranslate:5000
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      libretranslate:
        condition: service_started
    networks:
      - app-network

  db:
    container_name: iron-journal-db
    hostname: mongodb
    image: mongo:8.0
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017'
    networks:
      - app-network
    command: ["mongod", "--bind_ip", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost", "--port", "27017", "--eval", "db.adminCommand({ ping: 1 })"]
      interval: 10s
      timeout: 10s
      retries: 5

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    hostname: redis
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis:/data
    networks:
      - app-network



  libretranslate:
    hostname: libretranslate
    restart: always
    image: libretranslate/libretranslate:v1.6.1
    ports:
      - '5000'
    networks:
      - app-network

volumes:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
