version: '3.8'

services:
  app:
    build:
      context: ./Backend
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - rabbitmq
      - libretranslate
    env_file:
      - ./Backend/.env
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - '5000:5000'
    networks:
      - app-network

volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  app-network:
    driver: bridge
