version: '3.8'

services:
  app:
    build: ./Backend
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - rabbitmq
      - libretranslate
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app                 # Mount your source code to enable hot reloading
      - /app/node_modules               # Prevent overwriting node_modules with the host folder
    networks:
      - app-network
    command: npm run dev                # Use development command for hot reloading (e.g., nodemon or Remix dev server)

  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - '5000:5000'
    networks:
      - app-network

volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  app-network:
    driver: bridge
