# Base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the app port
EXPOSE 3000

# Default environment set to development
ENV NODE_ENV=development

# Start the app in development mode (using the dev script in package.json)
CMD ["npm", "run", "dev", "--port", "3000", "--hostname", "0.0.0.0"]
